apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vibamart-hpa
  namespace: vibamart-production
  labels:
    app.kubernetes.io/name: vibamart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vibamart-web
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
