apiVersion: v1
kind: Namespace
metadata:
  name: vibamart-production
  labels:
    app.kubernetes.io/name: vibamart
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: vibamart-staging
  labels:
    app.kubernetes.io/name: vibamart
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: vibamart-dev
  labels:
    app.kubernetes.io/name: vibamart
    environment: development
