apiVersion: v1
kind: Service
metadata:
  name: vibamart-service
  namespace: vibamart-production
  labels:
    app.kubernetes.io/name: vibamart
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: vibamart-web
